### ISSUE TITLE
Add new sections to share blog's articles

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#91]
### Describe the solution you'd like

We have to share with users different informations:

- Tech updates
- Partnership
- Global purpose (like Energy Consumption article)
We have to think about segmentation of the website to share these informations that doesn't interest the same population, the same skills and the same importance

Tasks:
- [x] https://github.com/archethic-foundation/archethic-website/issues/86
- [x] https://github.com/archethic-foundation/archethic-website/issues/87
- [x] https://github.com/archethic-foundation/archethic-website/issues/111

**Comment by redDwarf03** [comment]
- In community section, add tabs with different themes: (in order)
    - Global
    - Presse (see later)
    - Tech Updates
    - Partnership
   - [ ]  See in next marketing meeting the name of the article (@redDwarf03)
   - [ ]  See if we have to share article cross theme (@redDwarf03)
    
    → in mobile way, use big image under the tabs (vertical)
    
-  [ ] Change header of the website with section community link between “Archethic (UCO)” and “Developers” (to be validated in marketing meeting)
-  [ ] Change sequence of the website with section community between “Archethic (UCO)” and “Developers” (to be validated in marketing meeting)
-  [ ] Add “See all the blog” button to go to main screen of blog
-  [ ] Show with big image : last article (not the most important)
    - use excerpt properties in the blog to write the summary of the article

**Comment by redDwarf03** [comment]
after review with marketing's team, we don't have to use custom excerpt field because this field appears in front of blog article before the image.
So, we should change the field and use meta description
